import { getQuickWins } from './scoring.mjs';

/**
 * Generate a self-contained HTML report.
 */
export function reportHtml(report) {
  const quickWins = getQuickWins(report.categories, 10);
  const sorted = Object.entries(report.categories)
    .sort((a, b) => b[1].weight - a[1].weight);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Website Audit: ${esc(report.hostname)} - ${report.date}</title>
<style>
${CSS}
</style>
</head>
<body>
<div class="report">

  <!-- Header -->
  <header class="report-header">
    <div class="header-top">
      <div class="brand">cc-websiteaudit</div>
      <div class="meta">${report.date} &middot; ${report.pagesCrawled} pages crawled</div>
    </div>
    <h1>${esc(report.hostname)}</h1>
    <div class="url-display">${esc(report.url)}</div>
  </header>

  <!-- Overall Grade -->
  <section class="overall-grade">
    <div class="grade-circle ${gradeClass(report.overall.grade)}">
      <span class="grade-letter">${report.overall.grade}</span>
      <span class="grade-score">${report.overall.score}/100</span>
    </div>
    <div class="grade-label">Overall Score</div>
  </section>

  <!-- Site Profile -->
  ${report.siteProfile ? `
  <section class="site-profile">
    <h2>Site Profile</h2>
    <div class="profile-grid">
      <div class="profile-item">
        <div class="profile-label">Hosting</div>
        <div class="profile-value">${esc(report.siteProfile.hosting.join(', '))}</div>
      </div>
      <div class="profile-item">
        <div class="profile-label">Framework / CMS</div>
        <div class="profile-value">${esc(report.siteProfile.framework.join(', '))}</div>
      </div>
      ${report.siteProfile.server ? `
      <div class="profile-item">
        <div class="profile-label">Server</div>
        <div class="profile-value">${esc(report.siteProfile.server)}</div>
      </div>` : ''}
      ${report.siteProfile.additionalTech.length > 0 ? `
      <div class="profile-item profile-item-wide">
        <div class="profile-label">Other Technologies</div>
        <div class="profile-tags">
          ${report.siteProfile.additionalTech.map(t => `<span class="profile-tag">${esc(t)}</span>`).join('\n          ')}
        </div>
      </div>` : ''}
    </div>
  </section>` : ''}

  <!-- Category Summary -->
  <section class="category-summary">
    <h2>Category Scores</h2>
    <div class="category-grid">
${sorted.map(([id, cat]) => `
      <div class="category-card">
        <div class="cat-grade ${gradeClass(cat.grade)}">${cat.grade}</div>
        <div class="cat-info">
          <div class="cat-name">${esc(cat.name)}</div>
          <div class="cat-bar-track">
            <div class="cat-bar-fill ${barClass(cat.score)}" style="width: ${cat.score}%"></div>
          </div>
          <div class="cat-score">${cat.score}/100 &middot; Weight: ${Math.round(cat.weight * 100)}%</div>
        </div>
      </div>`).join('\n')}
    </div>
  </section>

  <!-- Quick Wins -->
  ${quickWins.length > 0 ? `
  <section class="quick-wins">
    <h2>Priority Actions</h2>
    <p class="section-desc">Ranked by impact-to-effort ratio. Fix these first for the biggest improvement.</p>
    <div class="wins-list">
${quickWins.map((qw, i) => `
      <div class="win-item ${qw.status === 'FAIL' ? 'win-fail' : 'win-warn'}">
        <div class="win-rank">${i + 1}</div>
        <div class="win-body">
          <div class="win-header">
            <span class="win-badge ${qw.status === 'FAIL' ? 'badge-fail' : 'badge-warn'}">${qw.status}</span>
            <span class="win-name">${esc(qw.name)}</span>
            <span class="win-tags">Impact: ${qw.impact}/5 &middot; Effort: ${qw.effort}/5</span>
          </div>
          <div class="win-detail">${esc(qw.detail)}</div>
        </div>
      </div>`).join('\n')}
    </div>
  </section>` : ''}

  <!-- Detailed Results -->
  <section class="detailed-results">
    <h2>Detailed Results</h2>
${sorted.map(([id, cat]) => `
    <div class="result-category">
      <div class="result-cat-header">
        <span class="result-cat-grade ${gradeClass(cat.grade)}">${cat.grade}</span>
        <h3>${esc(cat.name)}</h3>
        <span class="result-cat-score">${cat.score}/100</span>
      </div>
      <div class="checks-list">
${cat.checks.map(check => `
        <div class="check-item check-${check.status.toLowerCase()}">
          <div class="check-status">${statusLabel(check.status)}</div>
          <div class="check-body">
            <div class="check-name">${esc(check.name)}</div>
            <div class="check-detail">${esc(check.detail)}</div>
          </div>
        </div>`).join('\n')}
      </div>
    </div>`).join('\n')}
  </section>

  <!-- Footer -->
  <footer class="report-footer">
    <div>Generated by <strong>cc-websiteaudit</strong> v1.0.0 on ${report.date}</div>
    <div class="footer-note">Scores based on 35 checks across SEO, security, structured data, and AI readiness.</div>
  </footer>

</div>
</body>
</html>`;
}

function esc(str) {
  if (!str) return '';
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function gradeClass(grade) {
  if (grade.startsWith('A')) return 'grade-a';
  if (grade.startsWith('B')) return 'grade-b';
  if (grade.startsWith('C')) return 'grade-c';
  if (grade.startsWith('D')) return 'grade-d';
  return 'grade-f';
}

function barClass(score) {
  if (score >= 90) return 'bar-a';
  if (score >= 80) return 'bar-b';
  if (score >= 70) return 'bar-c';
  if (score >= 60) return 'bar-d';
  return 'bar-f';
}

function statusLabel(status) {
  switch (status) {
    case 'PASS': return '<span class="status-pass">PASS</span>';
    case 'WARN': return '<span class="status-warn">WARN</span>';
    case 'FAIL': return '<span class="status-fail">FAIL</span>';
    case 'SKIP': return '<span class="status-skip">SKIP</span>';
    default: return status;
  }
}

// ---------- Inline CSS ----------

const CSS = `
/* Reset & Base */
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

body {
  font-family: 'Segoe UI', -apple-system, BlinkMacSystemFont, 'Helvetica Neue', Arial, sans-serif;
  background: #f0f2f5;
  color: #1a1a2e;
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}

.report {
  max-width: 900px;
  margin: 0 auto;
  padding: 40px 24px;
}

/* Header */
.report-header {
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
  color: #fff;
  padding: 40px 48px;
  border-radius: 16px;
  margin-bottom: 32px;
}
.header-top {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-bottom: 16px;
  font-size: 13px;
  opacity: 0.8;
}
.brand { font-weight: 700; letter-spacing: 0.5px; text-transform: uppercase; font-size: 11px; }
.report-header h1 {
  font-size: 36px;
  font-weight: 800;
  letter-spacing: -0.5px;
  margin-bottom: 6px;
}
.url-display {
  font-size: 14px;
  opacity: 0.65;
  font-family: 'Consolas', 'SF Mono', monospace;
}

/* Overall Grade */
.overall-grade {
  text-align: center;
  margin: -56px auto 32px;
  position: relative;
  z-index: 2;
}
.grade-circle {
  display: inline-flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 140px;
  height: 140px;
  border-radius: 50%;
  background: #fff;
  box-shadow: 0 8px 32px rgba(0,0,0,0.12);
  border: 5px solid;
}
.grade-letter {
  font-size: 48px;
  font-weight: 900;
  line-height: 1;
}
.grade-score {
  font-size: 14px;
  font-weight: 600;
  opacity: 0.6;
  margin-top: 2px;
}
.grade-label {
  margin-top: 8px;
  font-size: 13px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 1px;
  color: #666;
}

/* Site Profile */
.site-profile {
  background: #fff;
  border-radius: 12px;
  padding: 32px;
  margin-bottom: 28px;
  box-shadow: 0 1px 4px rgba(0,0,0,0.06);
}
.profile-grid {
  display: grid;
  grid-template-columns: 1fr 1fr;
  gap: 20px;
  margin-top: 20px;
}
.profile-item {
  padding: 16px 20px;
  background: #f8f9fa;
  border-radius: 8px;
  border-left: 4px solid #2563eb;
}
.profile-item-wide {
  grid-column: 1 / -1;
}
.profile-label {
  font-size: 11px;
  font-weight: 700;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  color: #888;
  margin-bottom: 6px;
}
.profile-value {
  font-size: 16px;
  font-weight: 700;
  color: #1a1a2e;
}
.profile-tags {
  display: flex;
  flex-wrap: wrap;
  gap: 8px;
}
.profile-tag {
  display: inline-block;
  font-size: 12px;
  font-weight: 600;
  padding: 4px 12px;
  border-radius: 16px;
  background: #e8ecf0;
  color: #444;
}

/* Grade colors */
.grade-a { border-color: #059669; color: #059669; }
.grade-b { border-color: #2563eb; color: #2563eb; }
.grade-c { border-color: #d97706; color: #d97706; }
.grade-d { border-color: #ea580c; color: #ea580c; }
.grade-f { border-color: #dc2626; color: #dc2626; }

/* Section headings */
h2 {
  font-size: 22px;
  font-weight: 800;
  margin-bottom: 6px;
  color: #1a1a2e;
}
.section-desc {
  font-size: 14px;
  color: #666;
  margin-bottom: 20px;
}

/* Category Summary */
.category-summary {
  background: #fff;
  border-radius: 12px;
  padding: 32px;
  margin-bottom: 28px;
  box-shadow: 0 1px 4px rgba(0,0,0,0.06);
}
.category-grid {
  display: flex;
  flex-direction: column;
  gap: 16px;
  margin-top: 20px;
}
.category-card {
  display: flex;
  align-items: center;
  gap: 20px;
}
.cat-grade {
  width: 52px;
  height: 52px;
  border-radius: 10px;
  display: flex;
  align-items: center;
  justify-content: center;
  font-size: 20px;
  font-weight: 800;
  flex-shrink: 0;
  background: #f8f9fa;
}
.cat-grade.grade-a { background: #ecfdf5; color: #059669; }
.cat-grade.grade-b { background: #eff6ff; color: #2563eb; }
.cat-grade.grade-c { background: #fffbeb; color: #d97706; }
.cat-grade.grade-d { background: #fff7ed; color: #ea580c; }
.cat-grade.grade-f { background: #fef2f2; color: #dc2626; }
.cat-info { flex: 1; }
.cat-name { font-weight: 700; font-size: 15px; margin-bottom: 6px; }
.cat-bar-track {
  height: 8px;
  background: #e5e7eb;
  border-radius: 4px;
  overflow: hidden;
  margin-bottom: 4px;
}
.cat-bar-fill {
  height: 100%;
  border-radius: 4px;
  transition: width 0.6s ease;
}
.bar-a { background: #059669; }
.bar-b { background: #2563eb; }
.bar-c { background: #d97706; }
.bar-d { background: #ea580c; }
.bar-f { background: #dc2626; }
.cat-score { font-size: 12px; color: #888; }

/* Quick Wins */
.quick-wins {
  background: #fff;
  border-radius: 12px;
  padding: 32px;
  margin-bottom: 28px;
  box-shadow: 0 1px 4px rgba(0,0,0,0.06);
}
.wins-list { margin-top: 16px; }
.win-item {
  display: flex;
  gap: 16px;
  padding: 16px 0;
  border-bottom: 1px solid #f0f0f0;
}
.win-item:last-child { border-bottom: none; }
.win-rank {
  width: 32px;
  height: 32px;
  border-radius: 50%;
  background: #f0f2f5;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 800;
  font-size: 14px;
  color: #555;
  flex-shrink: 0;
}
.win-body { flex: 1; }
.win-header {
  display: flex;
  align-items: center;
  gap: 10px;
  flex-wrap: wrap;
  margin-bottom: 4px;
}
.win-badge {
  font-size: 10px;
  font-weight: 800;
  padding: 2px 8px;
  border-radius: 4px;
  text-transform: uppercase;
  letter-spacing: 0.5px;
}
.badge-fail { background: #fef2f2; color: #dc2626; }
.badge-warn { background: #fffbeb; color: #d97706; }
.win-name { font-weight: 700; font-size: 15px; }
.win-tags { font-size: 12px; color: #888; }
.win-detail { font-size: 13px; color: #555; line-height: 1.5; }

/* Detailed Results */
.detailed-results {
  background: #fff;
  border-radius: 12px;
  padding: 32px;
  margin-bottom: 28px;
  box-shadow: 0 1px 4px rgba(0,0,0,0.06);
}
.result-category {
  margin-top: 28px;
  padding-top: 24px;
  border-top: 1px solid #eee;
}
.result-category:first-of-type {
  margin-top: 16px;
  padding-top: 0;
  border-top: none;
}
.result-cat-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 16px;
}
.result-cat-grade {
  font-size: 14px;
  font-weight: 800;
  width: 40px;
  height: 40px;
  border-radius: 8px;
  display: flex;
  align-items: center;
  justify-content: center;
}
.result-cat-header h3 {
  font-size: 18px;
  font-weight: 700;
  flex: 1;
}
.result-cat-score {
  font-size: 14px;
  font-weight: 600;
  color: #888;
}

.checks-list {
  display: flex;
  flex-direction: column;
  gap: 2px;
}
.check-item {
  display: flex;
  gap: 14px;
  padding: 12px 16px;
  border-radius: 8px;
  align-items: flex-start;
}
.check-pass { background: #f8fdf9; }
.check-warn { background: #fffdf5; }
.check-fail { background: #fef8f8; }
.check-skip { background: #f8f9fa; }
.check-status { flex-shrink: 0; width: 48px; padding-top: 1px; }
.status-pass { color: #059669; font-weight: 800; font-size: 12px; }
.status-warn { color: #d97706; font-weight: 800; font-size: 12px; }
.status-fail { color: #dc2626; font-weight: 800; font-size: 12px; }
.status-skip { color: #9ca3af; font-weight: 800; font-size: 12px; }
.check-name { font-weight: 700; font-size: 14px; margin-bottom: 2px; }
.check-detail { font-size: 13px; color: #555; }

/* Footer */
.report-footer {
  text-align: center;
  padding: 24px 0;
  font-size: 13px;
  color: #999;
}
.footer-note { margin-top: 4px; font-size: 11px; }

/* Print / PDF styles */
@media print {
  body { background: #fff; }
  .report { padding: 0; max-width: 100%; }
  .report-header { border-radius: 0; }
  .overall-grade { margin-top: -40px; }
  section { break-inside: avoid; }
  .result-category { break-inside: avoid; }
}
`;
